---
name: Text-Glob
version: 0.08
author:
  - Richard Clamp <richardc@unixbeard.net>
abstract: match globbing patterns against text
license: perl
build_requires:
  Test::More: 0
provides:
  Text::Glob:
    file: lib/Text/Glob.pm
    version: 0.08
generated_by: Module::Build version 0.25
